Fix CVE Issues
wavefrontHQ/integrations pull request #55
Opened 2022-09-08 10:15 UTC by yogeshprasad

Upgrade Spring Boot and Gson version.

2022-09-08 10:53 UTC, dkuldeep22 approved these changes
LGTM!

2022-09-08 13:40 UTC, locke-chappel requested changes
Current version of Spring Boot is 2.7.3. Remaining on 2.6.4, while it fixes a number of vulnerabilities, does not resolve all detected issues.

Similarly the current version of gson is 2.9.1. While 2.8.9 does not yet have any detected vulnerabilities is there some technical reason why we can't upgrade to the current version? (2.8.9 is nearly a year old already.)

2022-09-13 05:49 UTC, gangadharaswamy approved these changes
LGTM

2022-09-27 08:49 UTC, yogeshprasad commented
@locke-chappel Will you please approve if this looks fine?

2022-09-27 14:28 UTC, locke-chappel requested changes

2022-09-27 14:28 UTC, locke-chappel commented on adm/pom.xml
> +            <version>4.10.0</version>
CVE-2021-0341 is not resolved by this change. com.squareup.okhttp:logging-interceptor has a transitive dependency on com.squareup.okhttp 2.7.5. The fix to upgrade the direct okhttp dependency is valid but since the group id changed from com.squareup.okhttp to com.squareup.okhttp3 this allows for redundant and potentially conflicting okhttp versions, specifically the transitive 2.7.5 version on the okhttp group and the updated 4.10.0 from okhttp3 group.

The project currently has two versions of okhttp now.

2022-09-27 14:28 UTC, locke-chappel commented on adm/pom.xml
> +        <version>2.7.3</version>
Due to timing of release spring boot is now on 2.7.4; however, even this latest spring boot version still uses a vulnerable snakeyaml version (CVE-2022-25857).

There are two options here - 1) a temporary fix where we override the snakeyaml version to the latest version which then has to be undone once spring boot releases a fixed version or 2) we accept Spring as-is and log a ticket associated with all the other snakeyaml tickets.

Option 2 seems like the better path but note that the SLA for snakeyaml is 14 days (CVSSv3 score of 7.5) so even with option 2 we may still be required to temporarily override the snakeyaml version to comply with our SLA.

2022-09-27 14:28 UTC, locke-chappel commented on adm/pom.xml
> +            <version>2.9.1</version>
LGTM

2022-09-27 15:11 UTC, locke-chappel commented on adm/pom.xml
> +        <version>2.7.3</version>
Regarding the 2.7.x release line for Spring Boot and Snakeyaml, this thread https://github.com/spring-projects/spring-boot/issues/32221 suggests it may not be coming. Towards the end they state that they cannot upgrade dependency major version (e.g. 1.30 to 1.31) in a maintenance mode release (which apparently 2.7.x is despite being the current release). Spring Boot 3 will have a fix but for 2.7.4+ we may have to exclude or override snakeyaml manually.

Note that what they did so was in the 2.7.4 release they added support for overriding snakeyaml 1.30 to 1.31 (and likely later too). Seems there is a breaking change in 1.30 -> 1.31 that required changes on Spring's side.

In any case Spring Boot 2.7.4 or later is required to even be able to resolve the snakeyaml issue and even then we likely will have to manually remove/override snakeyaml. It's unclear if snakeyaml is required even if application code doesn't yaml configs (e.g. internal and/or other spring components may use yaml and thus require snakeyaml so exclude with caution).

2022-10-03 09:34 UTC, yogeshprasad commented
@locke-chappel Please have a look and approve if things look fine.

2022-10-03 14:15 UTC, locke-chappel approved these changes
Assuming using snakeyaml 1.33 (e.g. > 1.30) with Spring Boot < 2.7.4 works at runtime this should be good. Note that according to the Spring team this may cause runtime a exception in some cases which is why they made a change in 2.7.4 to support snakeyaml 1.31+.

From a security scan point we are good.

2022-10-04 05:57 UTC, merged